In [ ]:
import torch

inputs = torch.tensor(
    [[0.43,0.15,0.89], # Your (x^1)
    [0.55,0.87,0.66], # journey (x^2)
    [0.57,0.85,0.64], # starts (x^3)
    [0.22,0.58,0.33], # with (x^4)
    [0.77,0.25,0.10], # one (x^5)
    [0.05,0.80,0.55]] # step (x^6)
)

attn_scores = torch.empty(6,6)

# 速度过慢
# for i,x_i in enumerate(inputs):
#     for j,x_j in enumerate(inputs):
#         attn_scores[i,j] = torch.dot(x_i,x_j)

attn_scores = inputs @ inputs.T
print(attn_scores)

attn_weights = torch.softmax(attn_scores,dim=1)
print(attn_weights)

attn_context_vecs = attn_weights @ inputs
print(attn_context_vecs)

In [11]:
import torch

inputs = torch.tensor(
    [[0.43,0.15,0.89], # Your (x^1)
    [0.55,0.87,0.66], # journey (x^2)
    [0.57,0.85,0.64], # starts (x^3)
    [0.22,0.58,0.33], # with (x^4)
    [0.77,0.25,0.10], # one (x^5)
    [0.05,0.80,0.55]] # step (x^6)
)

x_2 = inputs[1]
d_in = inputs.shape[1]
d_out = 2

torch.manual_seed(123)
W_query = torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)
W_key = torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)

query_2 = x_2 @ W_query
# key_2 = x_2 @ W_key
# value_2 = x_2 @ W_value

# print(query_2)

keys = inputs @ W_key
values = inputs @ W_value
print("keys.shape:",keys.shape)
print("values.shape:",values.shape)

keys_2 = keys[1]
attn_score_22 = query_2.dot(keys_2)
print(attn_score_22)

attn_score_2 = query_2 @ keys.T
print(attn_score_2)

d_k = keys.shape[-1]
attn_weights_2 = torch.softmax(attn_score_2 / d_k**0.5 ,dim=-1)
print(attn_weights_2)

context_vec_2 = attn_weights_2 @ values
print(context_vec_2)

keys.shape: torch.Size([6, 2])
values.shape: torch.Size([6, 2])
tensor(1.8524)
tensor([1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440])
tensor([0.1500, 0.2264, 0.2199, 0.1311, 0.0906, 0.1820])
tensor([0.3061, 0.8210])
